Add the option to fetch provider pacts with a specified tag
olga-vasylchenko/pact-jvm pull request #1
Opened 2016-12-12 16:02 UTC by olga-vasylchenko

@alon.peer - could you please review? Thanks.

2016-12-13 11:14 UTC, dmt approved these changes

2016-12-13 15:18 UTC, alonpeer requested changes
Looks good!
I think it's worth adding an example with a tag to https://github.com/olga-vasylchenko/pact-jvm/tree/master/pact-jvm-provider-sbt#verifying-pact-files-from-a-pact-broker, and mention that it requires pact-broker >= v1.12.0

2016-12-14 09:54 UTC, olga-vasylchenko commented
good idea @alonpeer , will add that to readme. Thanks.

2016-12-14 11:39 UTC, merged

2016-12-14 11:42 UTC, alonpeer commented on pact-jvm-provider-sbt/README.md
> +You can also verify all the latest pacts for a provider for all its consumer where pacts have a specified tag:
all its **consumers**

2016-12-14 11:43 UTC, alonpeer commented on pact-jvm-provider-sbt/README.md
> +        .hasPactsFromPactBroker(new URL("http://pact-broker.local"), "tagName"))
Should use `Option`:

```
.hasPactsFromPactBroker(new URL("http://pact-broker.local"), Some("tagName"))
```